app/controllers/character.py
from flask import Blueprint, render_template, request, redirect, url_for, abort, session, flash, jsonify
import app.models.character as actor_model

character = Blueprint('character', __name__)

# page de detail des acteurs
@character.route('/<identifiant>', methods=['GET'])
def show(identifiant):
	return render_template('character/show.html',
	                       character=actor_model.get_character(identifiant),
	                       items=actor_model.get_all_elements(identifiant))

app/controllers/movie.py
from flask import Blueprint, render_template, request, redirect, url_for, abort, session, flash, jsonify
import app.models.movie as movie_model

movie = Blueprint('movie', __name__)


# page d'accueil des films
@movie.route('/', methods=['GET'])
def index():
	return render_template('movie/index.html',
	                       top_rated=movie_model.get_top_rated_movies(6),
	                       most_commented=movie_model.get_most_commented_movies(6),
	                       most_interested=movie_model.get_most_interested_movies(6))


# page d'affichage d'un film avec la pagination
@movie.route('/<identifiant>', methods=['GET'], defaults={'page': 0})
@movie.route('/<identifiant>/<page>', methods=['GET'])
def show(identifiant, page):
	item = movie_model.show_movie(identifiant)
	if item is None:
		return redirect(request.referrer or '/')
	tab = []
	for i in range(0, round(movie_model.get_nb_comments(identifiant) / 20)):
		tab.append(i)
	return render_template('movie/show.html',
	                       item=item,
	                       page=page,
	                       tab=tab,
	                       countries=movie_model.get_countries(identifiant),
	                       casting=movie_model.get_casting(identifiant),
	                       user_review=movie_model.get_user_review(identifiant,
	                                                               session['id']) if 'id' in session else (),
	                       reviews=movie_model.get_reviews(identifiant, 20, page),
	                       genres=movie_model.get_genres(identifiant),
	                       wishlist=movie_model.get_user_wishlist(identifiant,
	                                                              session['id']) if 'id' in session else ())


# ajax pour ajouter une note
@movie.route('/<id>/review', methods=['POST'])
def review(id):
	test = movie_model.rate_movie(id, session['id'], request.form['rate'])
	return jsonify(test)


# page d'ajout d'un commentaire
@movie.route('/<id>/comment', methods=['POST'])
def comment(id):
	if session['id'] is None or request.form['review'] is None:
		abort(400)
	if movie_model.comment_movie(id, session['id'], request.form['review']) is True:
		flash('Your comment have been added', 'success')
	else:
		flash('The database is unavailable', 'error')
	return redirect(request.referrer or '/')


# page de suppression d'un commenataire
@movie.route('/<id>/delete_comment', methods=['GET'])
def delete_comment(id):
	print(id)
	if session['id'] is None:
		abort(403)
	movie_model.delete_comment(id, session['id'])
	return redirect(request.referrer or '/')


# page de suppression d'une note
@movie.route('/<id>/delete_rate', methods=['GET'])
def delete_rate(id):
	if session['id'] is None:
		abort(403)
	movie_model.delete_rate(id, session['id'])
	return redirect(request.referrer or '/')


# page pour changer le status d'un element dans la wishlist
@movie.route('/<id>/wishlist', methods=['GET'])
def wishlist(id):
	if session['id'] is None is None:
		abort(400)
	movie_model.wishlist_movie(id, session['id'])
	return redirect(request.referrer or '/')


# page des films les mieux notés
@movie.route('/top_rate', methods=['GET'], defaults={'page': 0})
@movie.route('/top_rate/<int:page>', methods=['GET'])
def best_rate(page):
	tab = []
	for i in range(0, round(movie_model.get_total_movie_number() / 20)):
		tab.append(i)
	
	return render_template('movie/top_rate.html',
	                       top_rated=movie_model.get_top_rated_movies(20, page),
	                       tab=tab,
	                       page=page)


# page des films les plus commentés
@movie.route('/most_commented', methods=['GET'], defaults={'page': 0})
@movie.route('/most_commented/<int:page>', methods=['GET'])
def most_commented(page):
	tab = []
	for i in range(0, round(movie_model.get_total_movie_number() / 20)):
		tab.append(i)
	return render_template('movie/most_commented.html',
	                       top_rated=movie_model.get_most_commented_movies(20, page),
	                       tab=tab,
	                       page=page)


# page des films les plus ajouter a la wishlist
@movie.route('/most_wishlisted', methods=['GET'], defaults={'page': 0})
@movie.route('/most_wishlisted/<int:page>', methods=['GET'])
def most_wishlisted(page):
	tab = []
	for i in range(0, round(movie_model.get_total_movie_number() / 20)):
		tab.append(i)
	return render_template('movie/most_wishlisted.html',
	                       top_rated=movie_model.get_most_interested_movies(20, page),
	                       tab=tab,
	                       page=page)

app/controllers/signup.py
from flask import Blueprint, render_template, request, redirect, url_for, abort, session, flash
import app.models.signup as user_model
import app.models.movie as movie_model
from pymysql import MySQLError

signup = Blueprint('signup', __name__)


# page de connexion
@signup.route('/login', methods=['GET'])
def login():
	if 'username' in session:
		flash(u'you are already logged in', 'info')
		return redirect(request.referrer or '/')
	
	return render_template('signup/login.html')


# page de check de connexion
@signup.route('/login', methods=['POST'])
def connect():
	user_exist = ()
	if 'username' in session:
		flash(u'you are already logged in', 'info')
		return redirect(request.referrer or '/')
	
	if request.form['username'] is None or request.form['password'] is None:
		return redirect(url_for('signup.login'))
	else:
		
		try:
			user_exist = user_model.user_exist(request.form['username'], request.form['password'])
		except MySQLError:
			print(MySQLError)
			abort(500)
			
		if user_exist['count'] == 1:
			session['username'] = request.form['username']
			session['id'] = user_exist['id']
			flash(u'Connected with success', 'success')
			return redirect('/')
		else:
			flash(u'Invalid username or password', 'error')
			return render_template('signup/login.html')


# page de deconnexion
@signup.route('/logout', methods=['GET'])
def logout():
	session.pop('username')
	session.pop('id')
	flash(u'You are now disconnected.', 'info')
	return redirect(request.referrer or '/')


# page de profil, onglet note
@signup.route('/profil/<int:id>', methods=['GET'])
def profil(id):
	
	if 'id' in session and session['id'] == id:
		own = 1
	else:
		own = 0
	return render_template('signup/profil.html',
	                       user=user_model.get_user(id),
	                       rates=movie_model.get_all_rates(id),
	                       own=own,
	                       id=id)


# page de profil, onglet commentaire
@signup.route('/profil/<int:id>/comment', methods=['GET'])
def comment(id):
	if 'id' in session and session['id'] == id:
		own = 1
	else:
		own = 0
	return render_template('signup/profil_comment.html',
	                       user=user_model.get_user(id),
	                       comments=movie_model.get_all_comment(id),
	                       own=own,
	                       id=id)


# page de profil, onglet preference
@signup.route('/profil/<int:id>/wishlist', methods=['GET'])
def wishlist(id):
	if 'id' in session and session['id'] == id:
		own = 1
	else:
		own = 0
	return render_template('signup/profil_wishlist.html',
	                       user=user_model.get_user(id),
	                       rates=movie_model.get_all_wishlisted(id),
	                       own=own,
	                       id=id)


# page de formulaire d'inscription
@signup.route('/register', methods=['GET'])
def register_form():
	return render_template('signup/register.html')


# page de soumission du formulaire d'inscription
@signup.route('/register', methods=['POST'])
def register():
	if (request.form['username'].strip() != '' or request.form['password'].strip() != '' or request.form[
		'first_name'].strip() != '' or request.form['last_name'].strip() != '' or request.form['email'].strip() != ''):
		try:
			user_model.create_user(request.form['username'], request.form['password'],
			                       request.form['first_name'], request.form['last_name'], request.form['email'])
			flash(u'User have been created', 'success')
			return redirect(url_for('signup.login'))
		except MySQLError:
			flash(u'Username or Email is already used', 'error')
			return render_template('signup/register.html')
	else:
		return render_template('signup/register.html')

templates/movie/index.html
{% extends "layout/home.html" %}

{% block content %}
    <h1><b>Movies</b></h1>

    <h3><i class="fa fa-sm fa-trophy"></i> Top rated movies<span class="float-right">
        <a href="{{ url_for('movie.best_rate') }}" class="btn btn-secondary">See all</a></span>
    </h3>

    <hr>
    <div class="row display-poster">
        {% for item in top_rated %}
            <div class="col-lg-2 col-md-4 col-sm-6">
                <div class="image-container">
                    <a href="{{ url_for('movie.show', identifiant=item.id) }}">
                        <img src="{{ item.picture }}">
                    </a>
                    <div class="centered">{{ item.moyenne }}</div>
                </div>
                <p><a href="{{ url_for('movie.show', identifiant=item.id) }}">{{ item.name }}</a></p>
            </div>
        {% endfor %}
    </div>

    <br>
    <h3><i class="fa fa-sm fa-comments"></i> Most commented movies<span class="float-right">
        <a href="{{ url_for('movie.most_commented') }}" class="btn btn-secondary">See all</a></span>
    </h3>

    <hr>
    <div class="row display-poster">

        {% for item in most_commented %}
            <div class="col-lg-2 col-md-4 col-sm-6">
                <div class="image-container">
                    <a href="{{ url_for('movie.show', identifiant=item.id) }}">
                        <img src="{{ item.picture }}">
                    </a>
                    <div class="centered">{{ item.moyenne }}</div>
                </div>
                <p><a href="{{ url_for('movie.show', identifiant=item.id) }}">{{ item.name }}</a></p>
            </div>
        {% endfor %}

    </div>

    <br>
    <h3><i class="fa fa-sm fa-bookmark"></i> Most interested movies<span class="float-right">
        <a href="{{ url_for('movie.most_wishlisted') }}" class="btn btn-secondary">See all</a></span>
    </h3>
    <hr>
    <div class="row display-poster">
        {% for item in most_interested %}
            <div class="col-lg-2 col-md-4 col-sm-6">
                <div class="image-container">
                    <a href="{{ url_for('movie.show', identifiant=item.id) }}">
                        <img src="{{ item.picture }}">
                    </a>
                    <div class="centered">{{ item.moyenne }}</div>
                </div>
                <p><a href="{{ url_for('movie.show', identifiant=item.id) }}">{{ item.name }}</a></p>
            </div>
        {% endfor %}
    </div>



{% endblock %}

templates/movie/most_commented.html
{% extends "layout/home.html" %}

{% block content %}

    <br>
    <h3><i class="fa fa-sm fa-trophy"></i> Top rated movies</h3>
    <hr>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {{ 'disabled' if  page | int - 1 < 0 }}">
                <a class="page-link"
                   href="{{ url_for('movie.most_commented', page=(page | int - 1 if page | int - 1 >= 0 else 0)) }}"
                   tabindex="-1">Previous</a>
            </li>
            {% for index in tab %}
                <li class="page-item {{ 'active' if page | int == index }}"><a class="page-link"
                                                                               href="{{ url_for('movie.most_commented', page=index) }}">{{ index + 1 }}</a>
                </li>
            {% endfor %}
            <li class="page-item {{ 'disabled' if (page | int + 1) not in tab }}">
                <a class="page-link"
                   href="{{ url_for('movie.most_commented', page=(page | int + 1 if (page | int + 1) in tab else page)) }}">Next</a>
            </li>
        </ul>
    </nav>

    {% for item in top_rated %}
        <div class="row display-poster">
            <div class="col-lg-2">
                <div class="image-container">
                    <a href="{{ url_for('movie.show', identifiant=item.id) }}">
                        <img src="{{ item.picture }}">
                    </a>
                </div>
            </div>
            <div class="col-lg-10 cn">
                <div class="inner">
                    <h2><a href="{{ url_for('movie.show', identifiant=item.id) }}">{{ item.name }} ({{ item.release_year }})</a></h2>
                    <p class="description">{{ item.description }}</p>
                </div>
            </div>
        </div>
        <br>
    {% endfor %}

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {{ 'disabled' if  page | int - 1 < 0 }}">
                <a class="page-link"
                   href="{{ url_for('movie.most_commented', page=(page | int - 1 if page | int - 1 >= 0 else 0)) }}"
                   tabindex="-1">Previous</a>
            </li>
            {% for index in tab %}
                <li class="page-item {{ 'active' if page | int == index }}"><a class="page-link"
                                                                               href="{{ url_for('movie.most_commented', page=index) }}">{{ index + 1 }}</a>
                </li>
            {% endfor %}
            <li class="page-item {{ 'disabled' if (page | int + 1) not in tab }}">
                <a class="page-link"
                   href="{{ url_for('movie.most_commented', page=(page | int + 1 if (page | int + 1) in tab else page)) }}">Next</a>
            </li>
        </ul>
    </nav>
{% endblock %}

templates/movie/most_wishlisted.html
{% extends "layout/home.html" %}

{% block content %}

    <br>
    <h3><i class="fa fa-sm fa-trophy"></i> Top rated movies</h3>
    <hr>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {{ 'disabled' if  page | int - 1 < 0 }}">
                <a class="page-link"
                   href="{{ url_for('movie.most_wishlisted', page=(page | int - 1 if page | int - 1 >= 0 else 0)) }}"
                   tabindex="-1">Previous</a>
            </li>
            {% for index in tab %}
                <li class="page-item {{ 'active' if page | int == index }}"><a class="page-link"
                                                                               href="{{ url_for('movie.most_wishlisted', page=index) }}">{{ index + 1 }}</a>
                </li>
            {% endfor %}
            <li class="page-item {{ 'disabled' if (page | int + 1) not in tab }}">
                <a class="page-link"
                   href="{{ url_for('movie.most_wishlisted', page=(page | int + 1 if (page | int + 1) in tab else page)) }}">Next</a>
            </li>
        </ul>
    </nav>

    {% for item in top_rated %}
        <div class="row display-poster">
            <div class="col-lg-2">
                <div class="image-container">
                    <a href="{{ url_for('movie.show', identifiant=item.id) }}">
                        <img src="{{ item.picture }}">
                    </a>
                </div>
            </div>
            <div class="col-lg-10 cn">
                <div class="inner">
                    <h2><a href="{{ url_for('movie.show', identifiant=item.id) }}">{{ item.name }} ({{ item.release_year }})</a></h2>
                    <p class="description">{{ item.description }}</p>
                </div>
            </div>
        </div>
        <br>
    {% endfor %}

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {{ 'disabled' if  page | int - 1 < 0 }}">
                <a class="page-link"
                   href="{{ url_for('movie.most_wishlisted', page=(page | int - 1 if page | int - 1 >= 0 else 0)) }}"
                   tabindex="-1">Previous</a>
            </li>
            {% for index in tab %}
                <li class="page-item {{ 'active' if page | int == index }}"><a class="page-link"
                                                                               href="{{ url_for('movie.most_wishlisted', page=index) }}">{{ index + 1 }}</a>
                </li>
            {% endfor %}
            <li class="page-item {{ 'disabled' if (page | int + 1) not in tab }}">
                <a class="page-link"
                   href="{{ url_for('movie.most_wishlisted', page=(page | int + 1 if (page | int + 1) in tab else page)) }}">Next</a>
            </li>
        </ul>
    </nav>
{% endblock %}

templates/movie/show.html
{% extends "layout/home.html" %}

{% block header_content %}

    <br>

{% endblock %}

{% block content %}
    <div class="row display-poster">
        <div class="col-lg-2">
            <div class="image-container">
                <img src="{{ item.picture }}" class="show-picture">
                {% if item.moyenne %}
                    <div class="centered">{{ item.moyenne | round(1) }}</div>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-5 cn">
            <div class="inner">
                <h2>{{ item.name }} ({{ item.release_year }})</h2>
                {% if session['id'] %}
                    <span class="rating"></span>
                    <div class="button-set">
                        <a href="{{ url_for('movie.wishlist', id=item.id) }}"
                           class="btn btn-outline-secondary {{ 'text-success' if wishlist }}" title="add to interest"><i
                                class="fas fa-bookmark"></i> Wishlist</a>
                        <a href="#" class="btn btn-outline-secondary" data-toggle="modal" data-target="#review"
                           title="comment"><i class="fas fa-comments"></i> Review</a>
                    </div>
                {% endif %}
            </div>

        </div>
    </div>

    <hr>
    <div class="row">
        {% if item.description %}
            <div class="col-lg-12">
                <dl>
                    <dt>Synopsis</dt>
                    <dd>{{ item.description }}</dd>
                </dl>
            </div>
        {% endif %}
        {% if item.release_year %}
            <div class="col-lg-6">
                <dl>
                    <dt>Release</dt>
                    <dd>{{ item.release_year }}</dd>
                </dl>
            </div>
        {% endif %}
        {% if item.duration %}
            <div class="col-lg-6">
                <dl>
                    <dt>Duration</dt>
                    <dd>
                        {{ (item.duration) | string + 'm' }}
                    </dd>
                </dl>
            </div>
        {% endif %}
        {% if item.awards %}
            <div class="col-lg-6">
                <dl>
                    <dt>Awards</dt>
                    <dd>
                        {{ item.awards }}
                    </dd>
                </dl>
            </div>
        {% endif %}
        {% if item.production %}
            <div class="col-lg-6">
                <dl>
                    <dt>Production</dt>
                    <dd>
                        {{ item.production }}
                    </dd>
                </dl>
            </div>
        {% endif %}
        {% if item.box_office %}
            <div class="col-lg-6">
                <dl>
                    <dt>Box office</dt>
                    <dd>
                        {{ '{:,}'.format(item.box_office).replace(',', ' ') }}$
                    </dd>
                </dl>
            </div>
        {% endif %}
        {% if item.website %}
            <div class="col-lg-6">
                <dl>
                    <dt>Website</dt>
                    <dd>
                        <a href="{{ item.website }}">{{ item.website }}</a>
                    </dd>
                </dl>
            </div>
        {% endif %}
        {% if item.rated %}
            <div class="col-lg-6">
                <dl>
                    <dt>Rated</dt>
                    <dd>
                        {{ item.rated }}
                    </dd>
                </dl>
            </div>
        {% endif %}
        {% if countries %}
            <div class="col-lg-6">
                <dl>
                    <dt>Country</dt>
                    <dd>
                        {% for country in countries %}
                            {{ country.name }}
                        {% endfor %}
                    </dd>
                </dl>
            </div>
        {% endif %}
        {% if genres %}
            <div class="col-lg-6">
                <dl>
                    <dt>Genre</dt>
                    <dd>
                        {% for genre in genres %}
                            {{ genre.name }}
                        {% endfor %}
                    </dd>
                </dl>
            </div>
        {% endif %}
    </div>
    {% if casting %}
        <h3><i class="fa fa-sm fa-users"></i> Casting</h3>
        <hr>
        <div class="row display-poster">
            {% for character in casting %}
                <div class="col-lg-2 col-md-4 col-sm-6">
                    <a href="{{ url_for('character.show', identifiant=character.id) }}">
                        <div class="image-container">
                            {% if character.picture %}
                                <img class="portrait"
                                     src="{{ character.picture }}">
                            {% else %}
                                <img class="portrait"
                                     src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg">
                            {% endif %}
                            <div class="bottomed poste">{{ character.role }}</div>
                        </div>
                        <p>{{ character.fullname }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% if reviews %}
        <h3><i class="fas fa-comments"></i> Review</h3>
        <hr>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item {{ 'disabled' if  page | int - 1 < 0 }}">
                    <a class="page-link"
                       href="{{ url_for('movie.show', page=(page | int - 1 if page | int - 1 >= 0 else 0), identifiant=item.id) }}"
                       tabindex="-1">Previous</a>
                </li>
                {% for index in tab %}
                    <li class="page-item {{ 'active' if page | int == index }}"><a class="page-link"
                                                                                   href="{{ url_for('movie.show', page=index, identifiant=item.id) }}">{{ index + 1 }}</a>
                    </li>
                {% endfor %}
                <li class="page-item {{ 'disabled' if (page | int + 1) not in tab }}">
                    <a class="page-link"
                       href="{{ url_for('movie.show', page=(page | int + 1 if (page | int + 1) in tab else page), identifiant=item.id) }}">Next</a>
                </li>
            </ul>
        </nav>
        {% for review in reviews %}
            {% if review.comment %}
                <dl>
                    <dt><a href="{{ url_for('signup.profil', id=review.id) }}">{{ review.username }}</a></dt>
                    <dd>
                        {{ review.comment }}
                    </dd>
                </dl>
            {% endif %}
        {% endfor %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item {{ 'disabled' if  page | int - 1 < 0 }}">
                    <a class="page-link"
                       href="{{ url_for('movie.show', page=(page | int - 1 if page | int - 1 >= 0 else 0), identifiant=item.id) }}"
                       tabindex="-1">Previous</a>
                </li>
                {% for index in tab %}
                    <li class="page-item {{ 'active' if page | int == index }}"><a class="page-link"
                                                                                   href="{{ url_for('movie.show', page=index, identifiant=item.id) }}">{{ index + 1 }}</a>
                    </li>
                {% endfor %}
                <li class="page-item {{ 'disabled' if (page | int + 1) not in tab }}">
                    <a class="page-link"
                       href="{{ url_for('movie.show', page=(page | int + 1 if (page | int + 1) in tab else page), identifiant=item.id) }}">Next</a>
                </li>
            </ul>
        </nav>
    {% endif %}

    <div class="modal fade" id="review" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <form action="/movie/{{ item.id }}/comment" class="modal-content" method="post">
                <div class="modal-header">
                    <h5 class="modal-title">Review</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Review:</label>
                        <textarea class="form-control" rows="3" name="review">{% if user_review.comment %}
                            {{ user_review.comment }}{% endif %}</textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Valider">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block js_local %}

    <script>
        $(".rating").starRating({
            initialRating: {{ user_review.rate if user_review.rate else 0 }},
            totalStars: {{ 5*2 }},
            disableAfterRate: false,
            starSize: 30,
            useFullStars: true,
            callback: (currentRating, $el) => {
                $.post("/movie/{{ item.id }}/review", {
                    rate: currentRating
                }, (data, status) => {
                    console.log(data);
                    if (data === true) {
                        toastr['success']('Your rate have been saved');
                    } else {
                        toastr['error']('The database is unavailable');
                    }
                });
            }
        });
    </script>

{% endblock %}


templates/movie/top_rate.html
{% extends "layout/home.html" %}

{% block content %}

    <br>
    <h3><i class="fa fa-sm fa-trophy"></i> Top rated movies</h3>
    <hr>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {{ 'disabled' if  page | int - 1 < 0 }}">
                <a class="page-link"
                   href="{{ url_for('movie.best_rate', page=(page | int - 1 if page | int - 1 >= 0 else 0)) }}"
                   tabindex="-1">Previous</a>
            </li>
            {% for index in tab %}
                <li class="page-item {{ 'active' if page | int == index }}"><a class="page-link"
                                                                               href="{{ url_for('movie.best_rate', page=index) }}">{{ index + 1 }}</a>
                </li>
            {% endfor %}
            <li class="page-item {{ 'disabled' if (page | int + 1) not in tab }}">
                <a class="page-link"
                   href="{{ url_for('movie.best_rate', page=(page | int + 1 if (page | int + 1) in tab else page)) }}">Next</a>
            </li>
        </ul>
    </nav>

    {% for item in top_rated %}

        <div class="row display-poster">
            <div class="col-lg-2">
                <div class="image-container">
                    <a href="{{ url_for('movie.show', identifiant=item.id) }}">
                        <img src="{{ item.picture }}">
                    </a>
                    {% if item.moyenne %}
                        <div class="centered">{{ item.moyenne | round(1) }}</div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-10 cn">
                <div class="inner">
                    <h2><a href="{{ url_for('movie.show', identifiant=item.id) }}">{{ item.name }} ({{ item.release_year }})</a></h2>
                    <p class="description">{{ item.description }}</p>
                </div>
            </div>
        </div>
        <br>
    {% endfor %}

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {{ 'disabled' if  page | int - 1 < 0 }}">
                <a class="page-link"
                   href="{{ url_for('movie.best_rate', page=(page | int - 1 if page | int - 1 >= 0 else 0)) }}"
                   tabindex="-1">Previous</a>
            </li>
            {% for index in tab %}
                <li class="page-item {{ 'active' if page | int == index }}"><a class="page-link"
                                                                               href="{{ url_for('movie.best_rate', page=index) }}">{{ index + 1 }}</a>
                </li>
            {% endfor %}
            <li class="page-item {{ 'disabled' if (page | int + 1) not in tab }}">
                <a class="page-link"
                   href="{{ url_for('movie.best_rate', page=(page | int + 1 if (page | int + 1) in tab else page)) }}">Next</a>
            </li>
        </ul>
    </nav>
{% endblock %}