app/models/signup.py
from flask import abort
import app.models.database as _database


# permet de savoir si un couple utilisateur / password existe
def user_exist(username, password):
	conn = _database.connection()
	
	try:
		with conn.cursor() as cursor:
			sql = "SELECT COUNT(*) AS count, id FROM users WHERE username = %s AND password = MD5(%s)"
			cursor.execute(sql, (username, password))
			result = cursor.fetchone()
	
	finally:
		conn.close()
	
	return result


# cree un utilisateur
def create_user(username, password, first_name, last_name, email):
	conn = _database.connection()
	
	with conn.cursor() as cursor:
		sql = "INSERT INTO users (username, email, first_name, last_name, password) VALUE (%s, %s, %s, %s, MD5(%s));"
		cursor.execute(sql, (username, email, first_name, last_name, password))
		result = cursor.fetchone()
		conn.close()
	
	return result


# recupere les informations d'un utilisateur
def get_user(id):
	conn = _database.connection()
	
	try:
		with conn.cursor() as cursor:
			sql = "SELECT * FROM users WHERE id = %s"
			cursor.execute(sql, (id))
			result = cursor.fetchone()
			conn.close()
	except:
		abort(404)
	
	return result

app/controllers/signup.py
from flask import Blueprint, render_template, request, redirect, url_for, abort, session, flash
import app.models.signup as user_model
import app.models.movie as movie_model
from pymysql import MySQLError

signup = Blueprint('signup', __name__)


# page de connexion
@signup.route('/login', methods=['GET'])
def login():
	if 'username' in session:
		flash(u'you are already logged in', 'info')
		return redirect(request.referrer or '/')
	
	return render_template('signup/login.html')


# page de check de connexion
@signup.route('/login', methods=['POST'])
def connect():
	user_exist = ()
	if 'username' in session:
		flash(u'you are already logged in', 'info')
		return redirect(request.referrer or '/')
	
	if request.form['username'] is None or request.form['password'] is None:
		return redirect(url_for('signup.login'))
	else:
		
		try:
			user_exist = user_model.user_exist(request.form['username'], request.form['password'])
		except MySQLError:
			print(MySQLError)
			abort(500)
			
		if user_exist['count'] == 1:
			session['username'] = request.form['username']
			session['id'] = user_exist['id']
			flash(u'Connected with success', 'success')
			return redirect('/')
		else:
			flash(u'Invalid username or password', 'error')
			return render_template('signup/login.html')


# page de deconnexion
@signup.route('/logout', methods=['GET'])
def logout():
	session.pop('username')
	session.pop('id')
	flash(u'You are now disconnected.', 'info')
	return redirect(request.referrer or '/')


# page de profil, onglet note
@signup.route('/profil/<int:id>', methods=['GET'])
def profil(id):
	
	if 'id' in session and session['id'] == id:
		own = 1
	else:
		own = 0
	return render_template('signup/profil.html',
	                       user=user_model.get_user(id),
	                       rates=movie_model.get_all_rates(id),
	                       own=own,
	                       id=id)


# page de profil, onglet commentaire
@signup.route('/profil/<int:id>/comment', methods=['GET'])
def comment(id):
	if 'id' in session and session['id'] == id:
		own = 1
	else:
		own = 0
	return render_template('signup/profil_comment.html',
	                       user=user_model.get_user(id),
	                       comments=movie_model.get_all_comment(id),
	                       own=own,
	                       id=id)


# page de profil, onglet preference
@signup.route('/profil/<int:id>/wishlist', methods=['GET'])
def wishlist(id):
	if 'id' in session and session['id'] == id:
		own = 1
	else:
		own = 0
	return render_template('signup/profil_wishlist.html',
	                       user=user_model.get_user(id),
	                       rates=movie_model.get_all_wishlisted(id),
	                       own=own,
	                       id=id)


# page de formulaire d'inscription
@signup.route('/register', methods=['GET'])
def register_form():
	return render_template('signup/register.html')


# page de soumission du formulaire d'inscription
@signup.route('/register', methods=['POST'])
def register():
	if (request.form['username'].strip() != '' or request.form['password'].strip() != '' or request.form[
		'first_name'].strip() != '' or request.form['last_name'].strip() != '' or request.form['email'].strip() != ''):
		try:
			user_model.create_user(request.form['username'], request.form['password'],
			                       request.form['first_name'], request.form['last_name'], request.form['email'])
			flash(u'User have been created', 'success')
			return redirect(url_for('signup.login'))
		except MySQLError:
			flash(u'Username or Email is already used', 'error')
			return render_template('signup/register.html')
	else:
		return render_template('signup/register.html')

templates/signup/login.html
{% extends "layout/home.html" %}

{% block content %}
    <form class="form-signin" method="post" action="{{ url_for('signup.login') }}">
        <div class="text-center mb-4">
            <h1 class="h3 mb-3 font-weight-normal">Login</h1>
        </div>

        <div class="form-label-group input-divider">
            <input class="form-control" placeholder="Username" required="" autofocus="" type="text" name="username">
        </div>
        <div class="form-label-group">
            <input class="form-control" placeholder="Password" required="" type="password" name="password">
        </div>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <a class="btn btn-lg btn-secondary btn-block" href="{{ url_for('signup.register_form') }}">Register</a>
    </form>
{% endblock %}

templates/signup/profil.html
{% extends 'layout/home.html' %}

{% block content %}

    <br>
    <p class="username">{{ user.username | title }}</p>
    <p class="fullname">{{ user.first_name | title }} {{ user.last_name | title }}</p>

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="{{ url_for("signup.profil", id=id) }}">My rates</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for("signup.comment", id=id) }}">My comments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for("signup.wishlist", id=id) }}">My wishlist</a>
        </li>
    </ul>

    <br>
    {% for rate in rates %}
        <div class="row display-poster">
            <div class="col-lg-2 col-md-2">
                <div class="image-container">
                    <a href="{{ url_for('%s.show' % rate.type, identifiant=rate.id) }}">
                        <img src="{{ rate.picture }}">
                    </a>
                </div>
            </div>
            <div class="col-lg-10 col-md-10">
                <div class="inner">
                    <h2>{{ rate.name }} ({{ rate.release_year }})</h2>
                    <span class="rating" id="rate_{{ loop.index }}"></span>
                    {% if 'id' in session and id == session['id'] %}
                        <div>
                            <a href="{{ url_for('%s.delete_rate' % rate.type, id=rate.id) }}" class="btn btn-danger delete"><i class="fa fa-times"></i></a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div><hr>
    {% endfor %}

{% endblock %}


{% block js_local %}
    <script>
        {% for rate in rates %}
            $("#rate_{{ loop.index }}").starRating({
                    initialRating: {{ rate.rate }},
                    totalStars: {{ 5*2 }},
                    disableAfterRate: false,
                    readOnly: {{ 'false' if own else 'true' }},
                    starSize: 30,
                    useFullStars: true,
                    callback: (currentRating, $el) => {
                        $.post("/{{ rate.type }}/{{ rate.id }}/review", {
                            rate: currentRating
                        }, (data, status) => {
                            if (data === true) {
                                toastr['success']('Your rate have been saved');
                            } else {
                                toastr['error']('The database is unavailable');
                            }
                        });
                    }
                });
        {% endfor %}
    </script>
{% endblock %}

templates/signup/profil_comment.html
{% extends 'layout/home.html' %}

{% block content %}

    <br>
    <p class="username">{{ user.username | title }}</p>
    <p class="fullname">{{ user.first_name | title }} {{ user.last_name | title }}</p>

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for("signup.profil", id=id) }}">My rates</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{{ url_for("signup.comment", id=id) }}">My comments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for("signup.wishlist", id=id) }}">My wishlist</a>
        </li>
    </ul>

    <br>
    {% for comment in comments %}
        <div class="row display-poster">
            <div class="col-lg-2 col-md-2">
                <div class="image-container">
                    <a href="{{ url_for('%s.show' % comment.type, identifiant=comment.id) }}">
                        <img src="{{ comment.picture }}">
                    </a>
                </div>
            </div>
            <div class="col-lg-10 col-md-10">
                <div class="inner">
                    <h2>{{ comment.name }} ({{ comment.release_year }})</h2>
                    <p class="comment" id="{{ comment.id }}" type="{{ comment.type }}">"{{ comment.comment }}"</p>
                    {% if 'id' in session and id == session['id'] %}
                        <a href="#" class="btn btn-secondary edit"><i class="fa fa-pencil-alt"></i></a>
                        <a href="{{ url_for('%s.delete_comment' % comment.type, id=comment.id) }}" class="btn btn-danger delete"><i class="fa fa-times"></i></a>
                    {% endif %}
                </div>
            </div>
        </div><hr>
    {% endfor %}

    <div class="modal fade" id="review" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <form action="/movie/comment" class="modal-content" method="post" id="form-review">
                <div class="modal-header">
                    <h5 class="modal-title">Review</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Review:</label>
                        <textarea class="form-control" rows="3" name="review" id="form-value"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Valider">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block js_local %}

    <script>
        $(".edit").on('click', (e) => {
            let data = e.currentTarget.offsetParent.children[1].firstChild.data
            let id = e.currentTarget.offsetParent.children[1].id
            let type = e.currentTarget.offsetParent.children[1].attributes.type.value

            $('#form-review').attr('action', `/${type}/${id}/comment`);
            $('#form-value').html(data.replace('"', '').replace('"', ''))
            $("#review").modal('toggle')
        })

    </script>

{% endblock %}

templates/signup/profil_wishlist.html
{% extends 'layout/home.html' %}

{% block content %}

    <br>
    <p class="username">{{ user.username | title }}</p>
    <p class="fullname">{{ user.first_name | title }} {{ user.last_name | title }}</p>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for("signup.profil", id=id) }}">My rates</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for("signup.comment", id=id) }}">My comments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{{ url_for("signup.wishlist", id=id) }}">My wishlist</a>
        </li>
    </ul>

    <br>
    {% for rate in rates %}
        <div class="row display-poster">
            <div class="col-lg-2 col-md-2">
                <div class="image-container">
                    <a href="{{ url_for('%s.show' % rate.type, identifiant=rate.id) }}">
                        <img src="{{ rate.picture }}">
                    </a>
                </div>
            </div>
            <div class="col-lg-10 col-md-10">
                <div class="inner">
                    <h2>{{ rate.name }} ({{ rate.release_year }})</h2>
                    {% if 'id' in session and id == session['id'] %}
                        <a href="{{ url_for('%s.wishlist' % rate.type, id=rate.id) }}" class="btn btn-outline-secondary text-success" title="add to interest"><i
                            class="fas fa-bookmark"></i> Wishlist</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <hr>
    {% endfor %}

{% endblock %}

templates/signup/register.html
{% extends "layout/home.html" %}

{% block content %}
    <form class="form-signin" method="post" action="{{ url_for('signup.register') }}">
        <div class="text-center mb-4">
            <h1 class="h3 mb-3 font-weight-normal">Register</h1>
        </div>

        <div class="form-group">
            <input type="text" class="form-control" placeholder="Username" name="username"
                   value="{{ request.form.get('username') or '' }}" required>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <input type="text" class="form-control" placeholder="First name" name="first_name"
                       value="{{ request.form.get('first_name') or '' }}" required>
            </div>
            <div class="form-group col-md-6">
                <input type="text" class="form-control" placeholder="Last name" name="last_name"
                       value="{{ request.form.get('last_name') or '' }}" required>
            </div>
        </div>
        <div class="form-group">
            <input type="email" class="form-control" placeholder="Email" name="email"
                   value="{{ request.form.get('email') or '' }}"
                   pattern="[^@]+@[^@]+\.[a-zA-Z]{2,6}" required>
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" min="6" name="password"
                   value="{{ request.form.get('password') or '' }}" required>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
{% endblock %}